apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      
  - name: PostgreSQL-Airflow
    type: postgres
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    editable: false
    
  - name: PostgreSQL-Dev
    type: postgres
    url: postgres-dev:5432
    database: test_database
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
    editable: false